name: Clear commits
on:
  workflow_dispatch:
  schedule:
  - cron: 0 15 */3 * *
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: write
    steps:
      - uses: actions/checkout@v2
        with:
          ref: release
      - name: commit
        run: |
          git init
          git config --local user.name "actions"
          git config --local user.email "action@github.com"
          git checkout --orphan clearhistory
          git branch -D release
          git checkout --orphan release
          git add .
          git commit -m "ðŸš€ CI Updated"
          git remote set-url --add origin "https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}"
          git push -f -u origin release
